// M3.e Package B goldens — the miner's output, guided top-K menus, and the
// transported-reach threat model.
//
// The book module under test (src/agents/books.js) is GENERATED by
// tools/mine.mjs; these goldens lock its CONTRACT (provenance honesty,
// prior arithmetic), not its contents — re-mining with new wins must never
// break the suite. Guided-menu goldens lock the construction properties the
// blunder bank demanded: menus are plans, not dice; determinism holds; the
// pre-Package-B legacy bot is still constructible for the G1 gate.

import { createGame } from '../src/engine/state.js';
import * as stateApi from '../src/engine/state.js';
import { beginPlanning, applyAction, stateHash } from '../src/engine/engine.js';
import { viewFor } from '../src/engine/views.js';
import { legalActions, currentQuery } from '../src/engine/legal.js';
import { createHeuristicAgent, scorePlacement, scoreAction, effectiveWeights, WEIGHTS, WEIGHTS_V2, WEIGHTS_M3E } from '../src/agents/heuristic.js';
import { botRng } from '../src/agents/random.js';
import { BOOKS, BOOK_PROVENANCE, bookPrior, bookLines } from '../src/agents/books.js';
import { eq, ok } from './assert.js';

function freshPlanning(seed = 4242) {
  const s = createGame(6, { seed });
  beginPlanning(s);
  return s;
}

export const tests = [
  { name: 'book provenance is honest: every admitted source is hash-verified under the current revision; quarantined files never contribute', fn() {
    ok(BOOK_PROVENANCE.admitted.length > 0, 'the book mined at least one win');
    ok(BOOK_PROVENANCE.admitted.every(a => /^[0-9a-f]{8}$/.test(a.hash)), 'every admitted episode carries its verified hash');
    const admittedFiles = new Set(BOOK_PROVENANCE.admitted.map(a => a.file));
    ok(BOOK_PROVENANCE.quarantined.every(q => !admittedFiles.has(q.file)), 'quarantine and admission are disjoint');
    const games = Object.values(BOOKS).reduce((n, fb) => n + fb.games, 0);
    eq(games, BOOK_PROVENANCE.admitted.length, 'one admitted episode = one game in exactly one faction book');
  }},

  { name: 'bookPrior arithmetic: a placement seen in every game has prior 1; an unseen one has prior 0; fractions in between', fn() {
    let checked = 0;
    for (const [fid, fb] of Object.entries(BOOKS)) {
      const r1 = fb.rounds['1'] ?? fb.rounds[1];
      if (!r1) continue;
      for (const [rid, reg] of Object.entries(r1.regions)) {
        for (const [tok, n] of Object.entries(reg)) {
          eq(bookPrior(fid, 1, rid, tok), n / fb.games, `prior = count/games for ${fid} r1 ${rid} ${tok}`);
          checked++;
        }
      }
      eq(bookPrior(fid, 1, 'NOT_A_REGION', 'march'), 0, 'silent book = 0');
    }
    ok(checked > 10, `book carries real mass (${checked} priors checked)`);
  }},

  { name: 'guided menus: with a guide the planning menu is constructed top-K — set 0 is the greedy argmax of the guide\'s own lens, all sets distinct, all simulator-sound', fn() {
    const s = freshPlanning();
    const q = currentQuery(s);
    eq(q.type, 'submitOrders', 'a fresh game opens on planning');
    const agent = createHeuristicAgent({});
    const view = viewFor(s, q.faction);
    const guide = agent.makeGuide(view, q);
    const menu = legalActions(s, q, { guide });
    ok(menu.length >= 2, `guided menu offers alternatives (${menu.length})`);
    const sigs = new Set(menu.map(a => JSON.stringify(Object.entries(a.orders).sort())));
    eq(sigs.size, menu.length, 'every guided set is distinct');
    // set 0 must score at least as high as every other set under the guide
    const score = a => Object.entries(a.orders).reduce((t, [rid, o]) => t + guide.scorePlacement(rid, o), 0);
    const s0 = score(menu[0]);
    ok(menu.every(a => score(a) <= s0 + 1e-9), 'the greedy set leads its own menu');
    // soundness is the standing contract: applyAction accepts every item
    for (const a of menu) {
      const clone = structuredClone(s);
      applyAction(clone, a); // any throw fails the golden
    }
  }},

  { name: 'guided menus are deterministic and never perturb the unguided path (fuzz breadth preserved; game hash without a guide unchanged by the feature)', fn() {
    const s = freshPlanning();
    const q = currentQuery(s);
    const agent = createHeuristicAgent({});
    const guide = agent.makeGuide(viewFor(s, q.faction), q);
    const m1 = legalActions(s, q, { guide });
    const m2 = legalActions(s, q, { guide });
    eq(JSON.stringify(m1), JSON.stringify(m2), 'same state, same guide, same menu');
    const r1 = legalActions(s, q);
    const r2 = legalActions(s, q, {});
    eq(JSON.stringify(r1), JSON.stringify(r2), 'no guide = the M3.a sampler, byte-identical');
  }},

  { name: 'legacy bot (G1 incumbent) is constructible: guided:false has no makeGuide; tTransport:0 restores adjacency-only threat exactly', fn() {
    const legacy = createHeuristicAgent({ guided: false, weights: { tTransport: 0, bookBias: 0 } });
    eq(legacy.makeGuide, undefined, 'the legacy bot cannot guide menus');
    const modern = createHeuristicAgent({});
    ok(typeof modern.makeGuide === 'function', 'the shipping bot guides menus');
    // m3e42: V3 carries its own TUNED value for the M3E keys — the merge
    // check is that the ACTIVE vector's value wins, not the M3E default.
    eq(modern.weights.tTransport, WEIGHTS.tTransport, 'the active vector (V3) supplies the tuned M3E keys');
    ok(Math.abs(WEIGHTS.tTransport - WEIGHTS_M3E.tTransport) < 0.05, 'and it stayed within a nudge of the hand-set default');
    // m3e42: V3 legitimately CONTAINS the tuned M3E keys (it was tuned over
    // the full surface); the freeze discipline now reads: V1 and V2 are
    // untouched history, and V3 is born frozen.
    ok(WEIGHTS_V2.tTransport === undefined, 'V2 history untouched — the M3E keys never entered it');
    ok(Object.isFrozen(WEIGHTS), 'V3 is born frozen');
  }},

  { name: 'transported reach (blunder #5): an enemy army across a warship chain raises the threat a coastal defend answers — same board minus the fleet, no lift', fn() {
    // The setup map separates home seas (verified: zero lift at setup), so
    // the golden CONSTRUCTS the amphibious situation the owner's own wins
    // exploited: viewer holds a coastal region; an enemy fleet takes the
    // adjacent sea; an enemy army stands on another shore of that sea.
    const s = freshPlanning();
    const fid = currentQuery(s).faction;
    const base = viewFor(s, fid);
    const { adjacency, region } = stateApi;
    const ADJ = adjacency();
    let rigged = null;
    outer:
    for (const [rid, units] of Object.entries(base.unitsByRegion)) {
      if (!units.some(u => u.faction === fid)) continue;
      if (region(rid)?.kind !== 'land') continue;
      for (const sea of ADJ[rid] || []) {
        if (region(sea)?.kind !== 'maritime') continue;
        const far = [...(ADJ[sea] || [])].find(rr =>
          rr !== rid && region(rr)?.kind === 'land' && !(ADJ[rid] || new Set()).has(rr));
        if (far) { rigged = { rid, sea, far }; break outer; }
      }
    }
    ok(rigged, 'the map offers a coast, a sea, and a far shore');
    const enemy = base.factions.find(f => f !== fid);
    const withFleet = structuredClone(base);
    (withFleet.unitsByRegion[rigged.sea] ??= []).push({ faction: enemy, type: 'warship' });
    (withFleet.unitsByRegion[rigged.far] ??= []).push({ faction: enemy, type: 'infantry' }, { faction: enemy, type: 'infantry' });
    const noFleet = structuredClone(base);
    (noFleet.unitsByRegion[rigged.far] ??= []).push({ faction: enemy, type: 'infantry' }, { faction: enemy, type: 'infantry' });
    const W = { ...WEIGHTS_M3E, ...WEIGHTS };
    const o = { type: 'defend', mod: 1, starred: false };
    const threatened = scorePlacement(withFleet, fid, rigged.rid, o, W);
    const quiet = scorePlacement(noFleet, fid, rigged.rid, o, W);
    const Woff = { ...W, tTransport: 0 };
    ok(threatened > quiet + 1e-9, `the fleet makes the far army a threat (${threatened.toFixed(3)} > ${quiet.toFixed(3)})`);
    // Same board, transport off: the adjacent fleet still presses (it always
    // did), but the FAR ARMY vanishes from the threat — the difference is
    // exactly what the adjacency-only model was blind to (blunder #5).
    const adjacencyOnly = scorePlacement(withFleet, fid, rigged.rid, o, Woff);
    ok(threatened > adjacencyOnly + 1e-9,
      `the far army counts only through the chain (${threatened.toFixed(3)} > ${adjacencyOnly.toFixed(3)})`);
  }},

  { name: 'the teacher\'s line is ON the menu: a booked faction\'s guided planning menu contains its graded book line(s), simulator-approved', fn() {
    const s = freshPlanning();
    const q = currentQuery(s);
    ok(bookLines(q.faction, 1).length >= 1, `${q.faction} has a round-1 book`);
    const agent = createHeuristicAgent({ weights: { bookBias: 1.5 } }); // book ON
    const view = viewFor(s, q.faction);
    const menu = legalActions(s, q, { guide: agent.makeGuide(view, q) });
    const sigOf = orders => JSON.stringify(Object.entries(orders).sort());
    const menuSigs = new Set(menu.map(a => sigOf(a.orders)));
    const onMenu = bookLines(q.faction, 1).filter(l => menuSigs.has(sigOf(l.orders)));
    ok(onMenu.length >= 1, `at least one book line survived the simulator onto the menu (${onMenu.length})`);
    // Inert default: at stock weights (bookBias 0) the book must not narrow
    // menus — no lines are injected and the guide is pure live scoring.
    const stockAgent = createHeuristicAgent({});
    eq(stockAgent.weights.bookBias, 0, 'the book ships INERT by default (m3e31 finding)');
    eq(stockAgent.makeGuide(view, q).candidateSets().length, 0, 'no injection while inert');
  }},

  { name: 'graded soft selection (owner decision): with multiple book lines on the table the bot does NOT always take the top choice — distinct lines are played across seeds; picks are always book lines', fn() {
    const s = freshPlanning();
    const multi = Object.keys(BOOKS).find(f => bookLines(f, 1).length > 1);
    ok(multi, 'some faction carries multiple graded round-1 lines');
    const q = { type: 'submitOrders', faction: multi };
    const view = viewFor(s, multi);
    const sigOf = orders => JSON.stringify(Object.entries(orders).sort());
    const lineSigs = new Set(bookLines(multi, 1).map(l => sigOf(l.orders)));
    // Book ON: when a graded line leads the menu, the pick IS a book line.
    const on = createHeuristicAgent({ weights: { bookBias: 4 } }); // bias high enough that a line MUST lead — mechanism, not tuning
    const onMenu2 = legalActions(s, q, { guide: on.makeGuide(view, q) });
    for (let seed = 1; seed <= 10; seed++) {
      ok(lineSigs.has(sigOf(on.decide(view, q, onMenu2, botRng(seed)).orders)),
        'with the book live the leading line family wins the opening');
    }
    // Mechanism: at a warm temperature the sampling genuinely riffs — the
    // stock bookTemp is a tuning default, not the contract.
    // bookTemp scales against ABSOLUTE score gaps, which grow whenever scoring
    // strengthens (seat hunger widened them in m3e41) — the mechanism golden
    // samples HOT (bias 4 so lines lead; temp 6 so they genuinely riff)
    // and magnitude drift can never re-mask it.
    const warm = createHeuristicAgent({ weights: { bookBias: 4, bookTemp: 6 } });
    const warmMenu = legalActions(s, q, { guide: warm.makeGuide(view, q) });
    const picks = new Set();
    for (let seed = 1; seed <= 60; seed++) {
      const a = warm.decide(view, q, warmMenu, botRng(seed));
      ok(lineSigs.has(sigOf(a.orders)), 'warm sampling still only ever picks book lines');
      picks.add(sigOf(a.orders));
    }
    ok(picks.size >= 2, `the bot riffs among the teacher's lines (${picks.size} distinct across 60 warm seeds)`);
  }},

  { name: 'the book decays (owner decision): the same booked placement pulls harder in round 1 than round 3, and live scoring is untouched where the book is silent', fn() {
    const s = freshPlanning();
    const fid = currentQuery(s).faction;
    const view = viewFor(s, fid);
    const W = { ...WEIGHTS_M3E, ...WEIGHTS, bookBias: 1.5 }; // book ON
    const r1book = bookLines(fid, 1)[0].orders;
    const [rid, o] = Object.entries(r1book)[0];
    const at = round => {
      const v = structuredClone(view); v.round = round;
      return scorePlacement(v, fid, rid, o, W) - scorePlacement(v, fid, rid, o, { ...W, bookBias: 0 });
    };
    ok(at(1) > 0, 'round 1: the book pulls');
    ok(at(1) > at(3) - 1e-9 && at(3) >= 0, `the pull decays with rounds (r1 ${at(1).toFixed(3)} ≥ r3 ${at(3).toFixed(3)})`);
    const silent = { type: 'raid', mod: 0, starred: false };
    eq(scorePlacement(view, fid, rid, silent, W), scorePlacement(view, fid, rid, silent, { ...W, bookBias: 0 }),
      'where the book is silent, bookBias is invisible');
  }},

  { name: 'island fix (m3e34): an offshore fleet must not stop tax collection — rally stays full-value under transported-only threat, while defend still feels it', fn() {
    const s = freshPlanning();
    const fid = currentQuery(s).faction;
    const base = viewFor(s, fid);
    const { adjacency, region } = stateApi;
    const ADJ = adjacency();
    let rigged = null;
    outer:
    for (const [rid, units] of Object.entries(base.unitsByRegion)) {
      if (!units.some(u => u.faction === fid)) continue;
      if (region(rid)?.kind !== 'land') continue;
      for (const sea of ADJ[rid] || []) {
        if (region(sea)?.kind !== 'maritime') continue;
        const far = [...(ADJ[sea] || [])].find(rr =>
          rr !== rid && region(rr)?.kind === 'land' && !(ADJ[rid] || new Set()).has(rr));
        if (far) { rigged = { rid, sea, far }; break outer; }
      }
    }
    ok(rigged, 'a coast, a sea, a far shore');
    const enemy = base.factions.find(f => f !== fid);
    // Transported-ONLY threat: enemy fleet in a NON-adjacent sea chain would be
    // ideal, but the adjacent-sea fleet case is the harsher test — build the
    // pure version instead: army on the far shore, fleet in the sea, then
    // REMOVE the fleet's own adjacency by scoring rally (which now reads
    // adjacency only) vs defend (which reads full threat).
    const v = structuredClone(base);
    (v.unitsByRegion[rigged.sea] ??= []).push({ faction: enemy, type: 'warship' });
    (v.unitsByRegion[rigged.far] ??= []).push({ faction: enemy, type: 'infantry' }, { faction: enemy, type: 'infantry' });
    const W = { ...WEIGHTS_M3E, ...WEIGHTS };
    const rally = { type: 'rally', mod: 0, starred: false };
    // The warship IS adjacent, so adjacency pressure > 0 here; strip it to
    // isolate the phantom-landing case: fleet in a sea NOT adjacent to rid.
    const farSea = Object.keys(v.unitsByRegion).length && [...(ADJ[rigged.far] || [])].find(x =>
      region(x)?.kind === 'maritime' && !(ADJ[rigged.rid] || new Set()).has(x));
    if (farSea) {
      const v2 = structuredClone(base);
      (v2.unitsByRegion[farSea] ??= []).push({ faction: enemy, type: 'warship' });
      (v2.unitsByRegion[rigged.far] ??= []).push({ faction: enemy, type: 'infantry' });
      // transported threat may or may not reach rid via that chain; either
      // way rally must equal its quiet-board value:
      const quiet = scorePlacement(base, fid, rigged.rid, rally, W);
      eq(scorePlacement(v2, fid, rigged.rid, rally, W), quiet,
        'rally ignores non-adjacent fleets entirely');
    }
    // And with the adjacent fleet: defend feels the far army, rally does not
    // beyond the real adjacent warship.
    const Woff = { ...W, tTransport: 0 };
    eq(scorePlacement(v, fid, rigged.rid, rally, W),
       scorePlacement(v, fid, rigged.rid, rally, Woff),
      'tTransport has ZERO effect on rally scoring');
  }},

  { name: 'the zero-trap (m3e35, G2 forensics): perFaction multiplies and can NEVER lift a zeroed weight; perFactionSet overrides absolutely — both proven', fn() {
    const mult = { perFaction: { F3: { bookBias: 1.5 } } };
    eq(effectiveWeights(mult, 'F3').bookBias, 0,
      'the 600-game lesson: 0 × 1.5 = 0 — the book arm that silently ran stock');
    const abs = { perFactionSet: { F3: { bookBias: 1.5 } } };
    eq(effectiveWeights(abs, 'F3').bookBias, 1.5, 'perFactionSet lifts the zero');
    eq(effectiveWeights(abs, 'F1').bookBias, 0, 'other seats untouched');
    eq(effectiveWeights(abs, 'F3').tTransport, effectiveWeights(null, 'F3').tTransport,
      'unmentioned keys keep their defaults');
  }},

  { name: 'guided all-heuristic table plays a full game with zero rejections and is deterministic (the Package B fuzz)', fn() {
    const play = (seed, botSeed) => {
      let s = createGame(6, { seed });
      beginPlanning(s);
      const agents = Object.fromEntries(s.factions.map((f, i) => [f, createHeuristicAgent({ jitterSeed: botSeed * 131 + i })]));
      const rng = botRng(botSeed);
      let steps = 0;
      while (s.phase !== 'gameOver') {
        if (++steps > 6000) throw new Error('stuck');
        const q = currentQuery(s);
        const view = viewFor(s, q.faction);
        const menu = legalActions(s, q, { guide: agents[q.faction].makeGuide?.(view, q) });
        const a = agents[q.faction].decide(view, q, menu, rng);
        ok(menu.includes(a), 'picks are menu items, guided or not');
        s = applyAction(s, a).state;
      }
      return { hash: stateHash(s), steps };
    };
    const a = play(77001, 77001 * 31 + 7);
    ok(a.steps > 100, `a real game happened (${a.steps} actions)`);
    const b = play(77001, 77001 * 31 + 7);
    eq(a.hash, b.hash, 'guided play is deterministic per seed pair');
  }},
];

tests.push(
  { name: 'blunder #9 (m3e41): seat hunger — the SAME march into an unguarded enemy seat scores strictly higher with the hunger on; a plain field is untouched by it', fn() {
    const s = freshPlanning();
    const fid = currentQuery(s).faction;
    const view = viewFor(s, fid);
    const { region: reg, adjacency, controllerOf } = stateApi;
    const ADJ2 = adjacency();
    const empty = rid => !(view.unitsByRegion[rid] || []).length;
    const seat = Object.keys(ADJ2).find(r => reg(r)?.kind === 'land' && reg(r).muster > 0 && empty(r) && controllerOf(view, r) !== fid);
    const plain = Object.keys(ADJ2).find(r => reg(r)?.kind === 'land' && !(reg(r).muster > 0) && empty(r) && controllerOf(view, r) !== fid);
    ok(seat && plain, 'the board offers both');
    const origin = Object.keys(view.unitsByRegion).find(r => (view.unitsByRegion[r] || []).some(u => u.faction === fid && u.type !== 'warship'));
    const q = { type: 'resolveOrder', faction: fid }; // the QUERY is resolveOrder; the ACTION is resolveMarch
    const act = to => ({ faction: fid, type: 'resolveMarch', region: origin, moves: [{ to, units: { infantry: 1 } }] });
    const Won = { ...WEIGHTS_M3E, ...WEIGHTS };
    const Woff = { ...Won, mSeatHunger: 0 };
    ok(scoreAction(view, q, act(seat), Won) > scoreAction(view, q, act(seat), Woff) + 1e-9,
      'the hunger lifts the free castle');
    eq(scoreAction(view, q, act(plain), Won), scoreAction(view, q, act(plain), Woff),
      'a plain field feels nothing — the term is seat-specific');
  }},
  { name: 'blunder #10 (m3e41): sea tenure — sailing the LAST warship out of a sea guarding your coast is penalized; the same sortie from unguarded water is not', fn() {
    const s = freshPlanning();
    const fid = currentQuery(s).faction;
    const base = viewFor(s, fid);
    const { region: reg, adjacency, controllerOf } = stateApi;
    const ADJ2 = adjacency();
    const seas = Object.keys(ADJ2).filter(r => reg(r)?.kind === 'maritime' && !(base.unitsByRegion[r] || []).length);
    const guard = seas.find(sea => [...(ADJ2[sea] || [])].some(n => reg(n)?.kind !== 'maritime' && controllerOf(base, n) === fid));
    const open = seas.find(sea => ![...(ADJ2[sea] || [])].some(n => reg(n)?.kind !== 'maritime' && controllerOf(base, n) === fid));
    ok(guard && open, 'the map offers guarded and open waters (both empty)');
    const q = { type: 'resolveOrder', faction: fid }; // the QUERY is resolveOrder; the ACTION is resolveMarch
    const Won = { ...WEIGHTS_M3E, ...WEIGHTS };
    const Woff = { ...Won, mSeaTenure: 0 };
    const rigAndScore = (sea, W) => {
      const v = structuredClone(base);
      (v.unitsByRegion[sea] ??= []).push({ faction: fid, type: 'warship' });
      const dest = [...(ADJ2[sea] || [])].find(n => reg(n)?.kind === 'maritime' && !(v.unitsByRegion[n] || []).length) ?? [...(ADJ2[sea] || [])][0];
      return scoreAction(v, q, { faction: fid, type: 'resolveMarch', region: sea, moves: [{ to: dest, units: { warship: 1 } }] }, W);
    };
    ok(rigAndScore(guard, Won) < rigAndScore(guard, Woff) - 1e-9,
      'leaving the guarded lane costs — the tenure term bites');
    eq(rigAndScore(open, Won), rigAndScore(open, Woff),
      'open water carries no tenure — the same sortie is free there');
  }},
);
