// GENERATED by tools/mine.mjs — do not edit by hand; re-mine instead.
// Per-faction opening books from hash-verified human wins (M3.e Package B).
// Every admitted source replayed clean under rules revision 11 and
// reproduced its recorded hash; stale episodes are listed in provenance,
// quarantined per the check-episode doctrine (never silently learned from).

export const BOOK_PROVENANCE = {
  "minedAt": "2026-08-19T13:19:30.879Z",
  "rulesRevision": 11,
  "rounds": 3,
  "admitted": [
    {
      "file": "episode-1st-human-victory-f6-r4.json",
      "hash": "64b32cdc",
      "winner": "F3",
      "rounds": 4,
      "recordedRev": 8
    },
    {
      "file": "episode-baratheon-3-rounds-r3.json",
      "hash": "7bd78ce8",
      "winner": "F5",
      "rounds": 3,
      "recordedRev": 10
    },
    {
      "file": "episode-f3-aggressive-victory-r3.json",
      "hash": "be7ddc40",
      "winner": "F6",
      "rounds": 3,
      "recordedRev": 9
    },
    {
      "file": "episode-lancaster-r5.json",
      "hash": "1d82f522",
      "winner": "F2",
      "rounds": 5,
      "recordedRev": 11
    },
    {
      "file": "episode-neville-no-objective-different-opening-r4.json",
      "hash": "30c5ce10",
      "winner": "F6",
      "rounds": 4,
      "recordedRev": 11
    },
    {
      "file": "episode-neville-non-objective-r3.json",
      "hash": "820638c2",
      "winner": "F6",
      "rounds": 3,
      "recordedRev": 11
    },
    {
      "file": "episode-neville-r3.json",
      "hash": "f907c2dd",
      "winner": "F6",
      "rounds": 3,
      "recordedRev": 11
    },
    {
      "file": "episode-percy-fun-r10.json",
      "hash": "f4fd83a5",
      "winner": "F5",
      "rounds": 10,
      "recordedRev": 11
    },
    {
      "file": "episode-percy-r6.json",
      "hash": "a1ecad60",
      "winner": "F5",
      "rounds": 6,
      "recordedRev": 11
    },
    {
      "file": "episode-percy-tried-playing-with-a-mission-r8.json",
      "hash": "9d0244c9",
      "winner": "F5",
      "rounds": 8,
      "recordedRev": 11
    },
    {
      "file": "episode-shewolf-lancaster-standings-r10.json",
      "hash": "504406f6",
      "winner": "F2",
      "rounds": 10,
      "recordedRev": 11
    },
    {
      "file": "episode-swan-stafford-r6.json",
      "hash": "ee58b4de",
      "winner": "F4",
      "rounds": 6,
      "recordedRev": 11
    },
    {
      "file": "episode-tudor-awesomesauce-r10.json",
      "hash": "c4192b05",
      "winner": "F3",
      "rounds": 10,
      "recordedRev": 11
    },
    {
      "file": "episode-tudor-buggy-final-battle-calf-of-york--r5.json",
      "hash": "c51ccd8b",
      "winner": "F3",
      "rounds": 5,
      "recordedRev": 11
    },
    {
      "file": "episode-tudor-r8.json",
      "hash": "a5995747",
      "winner": "F3",
      "rounds": 8,
      "recordedRev": 11
    },
    {
      "file": "episode-tudor-v2-r8.json",
      "hash": "5b091c5b",
      "winner": "F3",
      "rounds": 8,
      "recordedRev": 11
    },
    {
      "file": "episode-tyrell-5-rounds-r5.json",
      "hash": "47859041",
      "winner": "F4",
      "rounds": 5,
      "recordedRev": 10
    },
    {
      "file": "episode-york-road-south--r7.json",
      "hash": "67b353f5",
      "winner": "F1",
      "rounds": 7,
      "recordedRev": 11
    }
  ],
  "quarantined": [
    {
      "file": "episode-1st-human-victory-lannisters-r5.json",
      "reason": "hash mismatch (recorded be307dfc, replayed 8f6dda15) — STALE, rules moved under it"
    },
    {
      "file": "episode-f1-victory-easy-4-rounds-r4.json",
      "reason": "hash mismatch (recorded b708051b, replayed 2b000612) — STALE, rules moved under it"
    },
    {
      "file": "episode-f3-win-different-opener-non-aggressive-u-r6.json",
      "reason": "hash mismatch (recorded 93d1af4b, replayed 1608de48) — STALE, rules moved under it"
    },
    {
      "file": "episode-france-human-win-conservative-until-poun-r6.json",
      "reason": "hash mismatch (recorded 4fcc90df, replayed a3179ebf) — STALE, rules moved under it"
    },
    {
      "file": "episode-greyjoy-almost-lost-to-baratheon--r6.json",
      "reason": "hash mismatch (recorded f9a930cc, replayed 656b1e2f) — STALE, rules moved under it"
    },
    {
      "file": "episode-iran-win-conservative-then-lightning-r5.json",
      "reason": "hash mismatch (recorded ea489e14, replayed c5ac3261) — STALE, rules moved under it"
    },
    {
      "file": "episode-kingmaker-error-stuck-r2.json",
      "reason": "no winner (unfinished or bug-report episode)"
    },
    {
      "file": "episode-spectate-awesome-last-minute-comeback-or-r10.json",
      "reason": "hash mismatch (recorded d6dd8ae4, replayed 1f225eb4) — STALE, rules moved under it"
    },
    {
      "file": "episode-tyrell-victory-awesome-new-tyrell-strate-r7.json",
      "reason": "hash mismatch (recorded 4dcf937e, replayed 0028087e) — STALE, rules moved under it"
    }
  ]
};

export const BOOKS = {
  "F3": {
    "games": 5,
    "rounds": {
      "1": {
        "regions": {
          "L20": {
            "support+1*": 1,
            "rally": 3,
            "march": 1
          },
          "L22": {
            "march": 1,
            "rally*": 3,
            "march+1*": 1
          },
          "S04": {
            "march-1": 3,
            "march": 1,
            "defend+1": 1
          }
        },
        "sets": {
          "L20:support+1* L22:march S04:march-1": {
            "orders": {
              "L20": {
                "type": "support",
                "mod": 1,
                "starred": true
              },
              "L22": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "S04": {
                "type": "march",
                "mod": -1,
                "starred": false
              }
            },
            "n": 1
          },
          "L20:rally L22:rally* S04:march": {
            "orders": {
              "L20": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L22": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "S04": {
                "type": "march",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L20:march L22:march+1* S04:march-1": {
            "orders": {
              "L20": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L22": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "S04": {
                "type": "march",
                "mod": -1,
                "starred": false
              }
            },
            "n": 1
          },
          "L20:rally L22:rally* S04:defend+1": {
            "orders": {
              "L20": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L22": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "S04": {
                "type": "defend",
                "mod": 1,
                "starred": false
              }
            },
            "n": 1
          },
          "L20:rally L22:rally* S04:march-1": {
            "orders": {
              "L20": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L22": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "S04": {
                "type": "march",
                "mod": -1,
                "starred": false
              }
            },
            "n": 1
          }
        }
      },
      "2": {
        "regions": {
          "L19": {
            "march": 1
          },
          "L20": {
            "support+1*": 1,
            "rally": 3
          },
          "L22": {
            "march-1": 1,
            "rally*": 3
          },
          "S04": {
            "raid": 2,
            "support": 1,
            "raid*": 1,
            "defend+1": 1
          },
          "S12": {
            "support": 2
          },
          "P08": {
            "rally": 3
          },
          "L04": {
            "march": 1
          },
          "L07": {
            "rally*": 1
          },
          "S03": {
            "support": 1
          }
        },
        "sets": {
          "L19:march L20:support+1* L22:march-1 S04:raid S12:support": {
            "orders": {
              "L19": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L20": {
                "type": "support",
                "mod": 1,
                "starred": true
              },
              "L22": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "S04": {
                "type": "raid",
                "mod": 0,
                "starred": false
              },
              "S12": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L20:rally L22:rally* P08:rally S04:raid S12:support": {
            "orders": {
              "L20": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L22": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "P08": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S04": {
                "type": "raid",
                "mod": 0,
                "starred": false
              },
              "S12": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L04:march L07:rally* S03:support S04:support": {
            "orders": {
              "L04": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L07": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "S03": {
                "type": "support",
                "mod": 0,
                "starred": false
              },
              "S04": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L20:rally L22:rally* P08:rally S04:raid*": {
            "orders": {
              "L20": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L22": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "P08": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S04": {
                "type": "raid",
                "mod": 0,
                "starred": true
              }
            },
            "n": 1
          },
          "L20:rally L22:rally* P08:rally S04:defend+1": {
            "orders": {
              "L20": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L22": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "P08": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S04": {
                "type": "defend",
                "mod": 1,
                "starred": false
              }
            },
            "n": 1
          }
        }
      },
      "3": {
        "regions": {
          "L18": {
            "march+1*": 1
          },
          "L20": {
            "march-1": 1,
            "march": 1,
            "defend+1*": 1,
            "rally": 1
          },
          "L21": {
            "defend+1*": 1
          },
          "S04": {
            "raid": 2,
            "march-1": 1,
            "support": 1,
            "raid*": 1
          },
          "S12": {
            "support+1*": 1,
            "support": 1
          },
          "L22": {
            "rally*": 3
          },
          "P08": {
            "rally": 3
          },
          "L04": {
            "march-1": 1
          },
          "L07": {
            "march": 1
          },
          "L09": {
            "support+1*": 1
          },
          "S03": {
            "support": 1
          }
        },
        "sets": {
          "L18:march+1* L20:march-1 L21:defend+1* S04:raid S12:support+1*": {
            "orders": {
              "L18": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "L20": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "L21": {
                "type": "defend",
                "mod": 2,
                "starred": true
              },
              "S04": {
                "type": "raid",
                "mod": 0,
                "starred": false
              },
              "S12": {
                "type": "support",
                "mod": 1,
                "starred": true
              }
            },
            "n": 1
          },
          "L20:march L22:rally* P08:rally S04:march-1 S12:support": {
            "orders": {
              "L20": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L22": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "P08": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S04": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "S12": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L04:march-1 L07:march L09:support+1* S03:support S04:support": {
            "orders": {
              "L04": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "L07": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L09": {
                "type": "support",
                "mod": 1,
                "starred": true
              },
              "S03": {
                "type": "support",
                "mod": 0,
                "starred": false
              },
              "S04": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L20:defend+1* L22:rally* P08:rally S04:raid*": {
            "orders": {
              "L20": {
                "type": "defend",
                "mod": 2,
                "starred": true
              },
              "L22": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "P08": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S04": {
                "type": "raid",
                "mod": 0,
                "starred": true
              }
            },
            "n": 1
          },
          "L20:rally L22:rally* P08:rally S04:raid": {
            "orders": {
              "L20": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L22": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "P08": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S04": {
                "type": "raid",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          }
        }
      }
    }
  },
  "F5": {
    "games": 4,
    "rounds": {
      "1": {
        "regions": {
          "L27": {
            "march+1*": 3,
            "march": 1
          },
          "L28": {
            "rally*": 3,
            "march+1*": 1
          },
          "S05": {
            "march": 1,
            "march-1": 3
          }
        },
        "sets": {
          "L27:march+1* L28:rally* S05:march": {
            "orders": {
              "L27": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "L28": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "S05": {
                "type": "march",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L27:march+1* L28:rally* S05:march-1": {
            "orders": {
              "L27": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "L28": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "S05": {
                "type": "march",
                "mod": -1,
                "starred": false
              }
            },
            "n": 2
          },
          "L27:march L28:march+1* S05:march-1": {
            "orders": {
              "L27": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L28": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "S05": {
                "type": "march",
                "mod": -1,
                "starred": false
              }
            },
            "n": 1
          }
        }
      },
      "2": {
        "regions": {
          "L21": {
            "defend+1": 1
          },
          "L28": {
            "march": 1,
            "rally": 1,
            "rally*": 2
          },
          "P07": {
            "march+1*": 1
          },
          "S05": {
            "support+1*": 1,
            "support": 1
          },
          "S06": {
            "support": 1,
            "march+1*": 3
          },
          "L25": {
            "rally*": 1,
            "march": 2
          }
        },
        "sets": {
          "L21:defend+1 L28:march P07:march+1* S05:support+1* S06:support": {
            "orders": {
              "L21": {
                "type": "defend",
                "mod": 1,
                "starred": false
              },
              "L28": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "P07": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "S05": {
                "type": "support",
                "mod": 1,
                "starred": true
              },
              "S06": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L25:rally* L28:rally S05:support S06:march+1*": {
            "orders": {
              "L25": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "L28": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S05": {
                "type": "support",
                "mod": 0,
                "starred": false
              },
              "S06": {
                "type": "march",
                "mod": 1,
                "starred": true
              }
            },
            "n": 1
          },
          "L25:march L28:rally* S06:march+1*": {
            "orders": {
              "L25": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L28": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "S06": {
                "type": "march",
                "mod": 1,
                "starred": true
              }
            },
            "n": 2
          }
        }
      },
      "3": {
        "regions": {
          "L21": {
            "rally": 1
          },
          "L22": {
            "march+1*": 1
          },
          "L25": {
            "rally": 1,
            "march-1": 2
          },
          "L28": {
            "march": 1,
            "rally*": 3
          },
          "P08": {
            "support": 1
          },
          "S04": {
            "march-1": 1
          },
          "S05": {
            "support+1*": 2,
            "support": 1
          },
          "S06": {
            "support": 2,
            "march-1": 1
          },
          "S07": {
            "march": 1,
            "march+1*": 2
          },
          "L34": {
            "march": 2
          },
          "P06": {
            "rally": 1
          }
        },
        "sets": {
          "L21:rally L22:march+1* L25:rally L28:march P08:support S04:march-1 S05:support+1* S06:support": {
            "orders": {
              "L21": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L22": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "L25": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L28": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "P08": {
                "type": "support",
                "mod": 0,
                "starred": false
              },
              "S04": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "S05": {
                "type": "support",
                "mod": 1,
                "starred": true
              },
              "S06": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L25:march-1 L28:rally* S05:support+1* S07:march": {
            "orders": {
              "L25": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "L28": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "S05": {
                "type": "support",
                "mod": 1,
                "starred": true
              },
              "S07": {
                "type": "march",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L25:march-1 L28:rally* L34:march P06:rally S05:support S06:support S07:march+1*": {
            "orders": {
              "L25": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "L28": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "L34": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "P06": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S05": {
                "type": "support",
                "mod": 0,
                "starred": false
              },
              "S06": {
                "type": "support",
                "mod": 0,
                "starred": false
              },
              "S07": {
                "type": "march",
                "mod": 1,
                "starred": true
              }
            },
            "n": 1
          },
          "L28:rally* L34:march S06:march-1 S07:march+1*": {
            "orders": {
              "L28": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "L34": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "S06": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "S07": {
                "type": "march",
                "mod": 1,
                "starred": true
              }
            },
            "n": 1
          }
        }
      }
    }
  },
  "F6": {
    "games": 4,
    "rounds": {
      "1": {
        "regions": {
          "L08": {
            "march": 2,
            "rally": 1,
            "march-1": 1
          },
          "L37": {
            "march-1": 2,
            "rally": 1,
            "march": 1
          },
          "P03": {
            "rally": 3,
            "march-1": 1
          },
          "S11": {
            "support": 3,
            "march": 1
          }
        },
        "sets": {
          "L08:march L37:march-1 P03:rally S11:support": {
            "orders": {
              "L08": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L37": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "P03": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S11": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 2
          },
          "L08:rally L37:rally P03:march-1 S11:march": {
            "orders": {
              "L08": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L37": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "P03": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "S11": {
                "type": "march",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L08:march-1 L37:march P03:rally S11:support": {
            "orders": {
              "L08": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "L37": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "P03": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S11": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          }
        }
      },
      "2": {
        "regions": {
          "L06": {
            "defend+1": 3
          },
          "L10": {
            "support": 1,
            "march": 2
          },
          "L14": {
            "march": 1,
            "march+1*": 2
          },
          "L37": {
            "rally": 1,
            "rally*": 1,
            "march-1": 1,
            "defend+1": 1
          },
          "P03": {
            "rally": 2,
            "support": 1
          },
          "S01": {
            "raid": 1
          },
          "S11": {
            "march-1": 2,
            "raid": 1
          },
          "L08": {
            "march+1*": 1
          },
          "S09": {
            "support+1*": 1
          },
          "S10": {
            "raid": 1
          }
        },
        "sets": {
          "L06:defend+1 L10:support L14:march L37:rally P03:rally S01:raid S11:march-1": {
            "orders": {
              "L06": {
                "type": "defend",
                "mod": 1,
                "starred": false
              },
              "L10": {
                "type": "support",
                "mod": 0,
                "starred": false
              },
              "L14": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L37": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "P03": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S01": {
                "type": "raid",
                "mod": 0,
                "starred": false
              },
              "S11": {
                "type": "march",
                "mod": -1,
                "starred": false
              }
            },
            "n": 1
          },
          "L08:march+1* L37:rally* S09:support+1* S10:raid": {
            "orders": {
              "L08": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "L37": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "S09": {
                "type": "support",
                "mod": 1,
                "starred": true
              },
              "S10": {
                "type": "raid",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L06:defend+1 L10:march L14:march+1* L37:march-1 P03:rally S11:raid": {
            "orders": {
              "L06": {
                "type": "defend",
                "mod": 1,
                "starred": false
              },
              "L10": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L14": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "L37": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "P03": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S11": {
                "type": "raid",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L06:defend+1 L10:march L14:march+1* L37:defend+1 P03:support S11:march-1": {
            "orders": {
              "L06": {
                "type": "defend",
                "mod": 1,
                "starred": false
              },
              "L10": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L14": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "L37": {
                "type": "defend",
                "mod": 1,
                "starred": false
              },
              "P03": {
                "type": "support",
                "mod": 0,
                "starred": false
              },
              "S11": {
                "type": "march",
                "mod": -1,
                "starred": false
              }
            },
            "n": 1
          }
        }
      },
      "3": {
        "regions": {
          "L10": {
            "march-1": 1,
            "rally*": 1
          },
          "L15": {
            "march": 1
          },
          "L37": {
            "raid": 1,
            "march+1*": 1,
            "march-1": 1
          },
          "P03": {
            "rally": 3
          },
          "P04": {
            "rally": 2,
            "raid": 1
          },
          "S01": {
            "raid": 1
          },
          "S10": {
            "support": 1,
            "support+1*": 1,
            "march": 1
          },
          "S11": {
            "support": 4
          },
          "S09": {
            "raid": 1
          },
          "L06": {
            "defend+1": 2
          },
          "L07": {
            "defend+1*": 1,
            "march+1*": 1
          },
          "L14": {
            "support+1*": 1
          },
          "L16": {
            "march+1*": 1
          },
          "L36": {
            "defend+1": 2
          }
        },
        "sets": {
          "L10:march-1 L15:march L37:raid P03:rally P04:rally S01:raid S10:support S11:support": {
            "orders": {
              "L10": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "L15": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L37": {
                "type": "raid",
                "mod": 0,
                "starred": false
              },
              "P03": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "P04": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S01": {
                "type": "raid",
                "mod": 0,
                "starred": false
              },
              "S10": {
                "type": "support",
                "mod": 0,
                "starred": false
              },
              "S11": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L10:rally* L37:march+1* S09:raid S10:support+1* S11:support": {
            "orders": {
              "L10": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "L37": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "S09": {
                "type": "raid",
                "mod": 0,
                "starred": false
              },
              "S10": {
                "type": "support",
                "mod": 1,
                "starred": true
              },
              "S11": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L06:defend+1 L07:defend+1* L14:support+1* L16:march+1* L36:defend+1 P03:rally P04:raid S11:support": {
            "orders": {
              "L06": {
                "type": "defend",
                "mod": 1,
                "starred": false
              },
              "L07": {
                "type": "defend",
                "mod": 2,
                "starred": true
              },
              "L14": {
                "type": "support",
                "mod": 1,
                "starred": true
              },
              "L16": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "L36": {
                "type": "defend",
                "mod": 1,
                "starred": false
              },
              "P03": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "P04": {
                "type": "raid",
                "mod": 0,
                "starred": false
              },
              "S11": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L06:defend+1 L07:march+1* L36:defend+1 L37:march-1 P03:rally P04:rally S10:march S11:support": {
            "orders": {
              "L06": {
                "type": "defend",
                "mod": 1,
                "starred": false
              },
              "L07": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "L36": {
                "type": "defend",
                "mod": 1,
                "starred": false
              },
              "L37": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "P03": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "P04": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S10": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "S11": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          }
        }
      }
    }
  },
  "F2": {
    "games": 2,
    "rounds": {
      "1": {
        "regions": {
          "L16": {
            "rally": 1,
            "march+1*": 1
          },
          "L36": {
            "rally*": 2
          },
          "P04": {
            "march": 1,
            "rally": 1
          },
          "S10": {
            "march+1*": 1,
            "march": 1
          }
        },
        "sets": {
          "L16:rally L36:rally* P04:march S10:march+1*": {
            "orders": {
              "L16": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L36": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "P04": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "S10": {
                "type": "march",
                "mod": 1,
                "starred": true
              }
            },
            "n": 1
          },
          "L16:march+1* L36:rally* P04:rally S10:march": {
            "orders": {
              "L16": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "L36": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "P04": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S10": {
                "type": "march",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          }
        }
      },
      "2": {
        "regions": {
          "L16": {
            "rally": 1
          },
          "L36": {
            "march+1*": 1,
            "rally*": 1
          },
          "S09": {
            "march": 1,
            "march-1": 1
          },
          "S10": {
            "march-1": 1,
            "march": 1
          },
          "S11": {
            "support+1*": 1
          },
          "L17": {
            "march+1*": 1
          },
          "P04": {
            "rally": 1
          }
        },
        "sets": {
          "L16:rally L36:march+1* S09:march S10:march-1 S11:support+1*": {
            "orders": {
              "L16": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L36": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "S09": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "S10": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "S11": {
                "type": "support",
                "mod": 1,
                "starred": true
              }
            },
            "n": 1
          },
          "L17:march+1* L36:rally* P04:rally S09:march-1 S10:march": {
            "orders": {
              "L17": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "L36": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "P04": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S09": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "S10": {
                "type": "march",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          }
        }
      },
      "3": {
        "regions": {
          "L16": {
            "rally": 1
          },
          "L36": {
            "rally*": 1,
            "march+1*": 1
          },
          "L37": {
            "march+1*": 1
          },
          "P03": {
            "rally": 1
          },
          "S01": {
            "raid": 1,
            "support+1*": 1
          },
          "S09": {
            "defend+1*": 1,
            "support": 1
          },
          "S10": {
            "march-1": 1,
            "support": 1
          },
          "S11": {
            "raid": 1
          },
          "L18": {
            "rally*": 1
          },
          "P04": {
            "rally": 1
          }
        },
        "sets": {
          "L16:rally L36:rally* L37:march+1* P03:rally S01:raid S09:defend+1* S10:march-1 S11:raid": {
            "orders": {
              "L16": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L36": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "L37": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "P03": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S01": {
                "type": "raid",
                "mod": 0,
                "starred": false
              },
              "S09": {
                "type": "defend",
                "mod": 2,
                "starred": true
              },
              "S10": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "S11": {
                "type": "raid",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          },
          "L18:rally* L36:march+1* P04:rally S01:support+1* S09:support S10:support": {
            "orders": {
              "L18": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "L36": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "P04": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S01": {
                "type": "support",
                "mod": 1,
                "starred": true
              },
              "S09": {
                "type": "support",
                "mod": 0,
                "starred": false
              },
              "S10": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          }
        }
      }
    }
  },
  "F4": {
    "games": 2,
    "rounds": {
      "1": {
        "regions": {
          "L30": {
            "march": 2
          },
          "L33": {
            "rally": 2
          },
          "S08": {
            "march-1": 2
          }
        },
        "sets": {
          "L30:march L33:rally S08:march-1": {
            "orders": {
              "L30": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L33": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S08": {
                "type": "march",
                "mod": -1,
                "starred": false
              }
            },
            "n": 2
          }
        }
      },
      "2": {
        "regions": {
          "L25": {
            "march": 1,
            "rally*": 1
          },
          "L31": {
            "support+1*": 1,
            "march": 1
          },
          "L33": {
            "march-1": 1,
            "rally": 1
          },
          "S07": {
            "march+1*": 2
          },
          "L30": {
            "march-1": 1
          },
          "S08": {
            "support": 1
          }
        },
        "sets": {
          "L25:march L31:support+1* L33:march-1 S07:march+1*": {
            "orders": {
              "L25": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L31": {
                "type": "support",
                "mod": 1,
                "starred": true
              },
              "L33": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "S07": {
                "type": "march",
                "mod": 1,
                "starred": true
              }
            },
            "n": 1
          },
          "L25:rally* L30:march-1 L31:march L33:rally S07:march+1* S08:support": {
            "orders": {
              "L25": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "L30": {
                "type": "march",
                "mod": -1,
                "starred": false
              },
              "L31": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L33": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S07": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "S08": {
                "type": "support",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          }
        }
      },
      "3": {
        "regions": {
          "L24": {
            "rally": 1
          },
          "L25": {
            "support": 1,
            "raid": 1
          },
          "L26": {
            "defend+1": 1
          },
          "L30": {
            "rally": 1,
            "march+1*": 1
          },
          "L31": {
            "march": 1,
            "rally*": 1
          },
          "S06": {
            "defend+1": 1
          },
          "S07": {
            "support": 1,
            "march": 1
          },
          "S08": {
            "march-1": 2
          },
          "L29": {
            "rally": 1
          },
          "L32": {
            "defend+1": 1
          },
          "L33": {
            "rally": 1
          },
          "S05": {
            "raid*": 1
          }
        },
        "sets": {
          "L24:rally L25:support L26:defend+1 L30:rally L31:march S06:defend+1 S07:support S08:march-1": {
            "orders": {
              "L24": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L25": {
                "type": "support",
                "mod": 0,
                "starred": false
              },
              "L26": {
                "type": "defend",
                "mod": 1,
                "starred": false
              },
              "L30": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L31": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "S06": {
                "type": "defend",
                "mod": 1,
                "starred": false
              },
              "S07": {
                "type": "support",
                "mod": 0,
                "starred": false
              },
              "S08": {
                "type": "march",
                "mod": -1,
                "starred": false
              }
            },
            "n": 1
          },
          "L25:raid L29:rally L30:march+1* L31:rally* L32:defend+1 L33:rally S05:raid* S07:march S08:march-1": {
            "orders": {
              "L25": {
                "type": "raid",
                "mod": 0,
                "starred": false
              },
              "L29": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L30": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "L31": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "L32": {
                "type": "defend",
                "mod": 1,
                "starred": false
              },
              "L33": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S05": {
                "type": "raid",
                "mod": 0,
                "starred": true
              },
              "S07": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "S08": {
                "type": "march",
                "mod": -1,
                "starred": false
              }
            },
            "n": 1
          }
        }
      }
    }
  },
  "F1": {
    "games": 1,
    "rounds": {
      "1": {
        "regions": {
          "L01": {
            "rally*": 1
          },
          "L04": {
            "march+1*": 1
          },
          "S02": {
            "march": 1
          }
        },
        "sets": {
          "L01:rally* L04:march+1* S02:march": {
            "orders": {
              "L01": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "L04": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "S02": {
                "type": "march",
                "mod": 0,
                "starred": false
              }
            },
            "n": 1
          }
        }
      },
      "2": {
        "regions": {
          "L01": {
            "march": 1
          },
          "L18": {
            "march+1*": 1
          },
          "P01": {
            "rally": 1
          },
          "S02": {
            "support": 1
          },
          "S03": {
            "support+1*": 1
          }
        },
        "sets": {
          "L01:march L18:march+1* P01:rally S02:support S03:support+1*": {
            "orders": {
              "L01": {
                "type": "march",
                "mod": 0,
                "starred": false
              },
              "L18": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "P01": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S02": {
                "type": "support",
                "mod": 0,
                "starred": false
              },
              "S03": {
                "type": "support",
                "mod": 1,
                "starred": true
              }
            },
            "n": 1
          }
        }
      },
      "3": {
        "regions": {
          "L01": {
            "rally*": 1
          },
          "L04": {
            "rally": 1
          },
          "L19": {
            "march+1*": 1
          },
          "P01": {
            "rally": 1
          },
          "S02": {
            "support": 1
          },
          "S03": {
            "raid": 1
          },
          "S12": {
            "defend+1*": 1
          }
        },
        "sets": {
          "L01:rally* L04:rally L19:march+1* P01:rally S02:support S03:raid S12:defend+1*": {
            "orders": {
              "L01": {
                "type": "rally",
                "mod": 0,
                "starred": true
              },
              "L04": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "L19": {
                "type": "march",
                "mod": 1,
                "starred": true
              },
              "P01": {
                "type": "rally",
                "mod": 0,
                "starred": false
              },
              "S02": {
                "type": "support",
                "mod": 0,
                "starred": false
              },
              "S03": {
                "type": "raid",
                "mod": 0,
                "starred": false
              },
              "S12": {
                "type": "defend",
                "mod": 2,
                "starred": true
              }
            },
            "n": 1
          }
        }
      }
    }
  }
};

/** Placement prior: how often the teacher put `tokenKey` on `rid` in `round`,
    as a fraction of that faction+round's games. 0 when the book is silent. */
export function bookPrior(fid, round, rid, tokenKey) {
  const fb = BOOKS[fid];
  const reg = fb?.rounds?.[round]?.regions?.[rid];
  if (!reg || !fb.games) return 0;
  return (reg[tokenKey] ?? 0) / fb.games;
}

/** All book placements for a faction+round: { rid: { tokenKey: count } } */
export function bookRegions(fid, round) {
  return BOOKS[fid]?.rounds?.[round]?.regions ?? null;
}

/** The teacher's distinct GRADED LINES for a faction+round:
    [{ orders, n }] — n = how many admitted wins played exactly this set.
    Sorted strongest grade first. */
export function bookLines(fid, round) {
  const sets = BOOKS[fid]?.rounds?.[round]?.sets;
  if (!sets) return [];
  return Object.values(sets).sort((a, b) => b.n - a.n);
}
